baseURL = "http://semiosis.github.io/"
languageCode = "en-us"
title = "semiosis"
theme = "hello-friend-ng"
paginate     = 10

# https://grep.app/search?q=dark&regexp=true&case=true&filter%5Bpath.pattern%5D%5B0%5D=config.toml
# ga dark config.toml
mode = "dark" # "dark", "auto", "light"  

[markup.goldmark.renderer]
unsafe= true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Signs, Natural Language and Coding"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Signs, Natural Language and Coding"
  keywords = "NLP, GPT-3"
  images = [""]

  [params.portrait]
    path        = "images/semiosis.png"
    maxwidth        = "7em"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "semiosis"
    subtitle = "Signs, Natural Language and Coding"
    keywords = "NLP GPT OpenAI EleutherAI Huggingface AGI"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "semiosis"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"

  [[menu.main]]
    identifier = "philosophy"
    name       = "PHIL"
    url        = "/philosophy/"

  [[menu.main]]
    identifier = "pen"
    name       = "Pen.el"
    url        = "/pen/"

  [[menu.main]]
    identifier = "ilambda"
    name       = "ùëñŒª ilambda"
    url        = "/ilambda/"

  [[menu.main]]
    identifier = "protocol"
    name       = "‡øã Semiosis Protocol"
    url        = "/protocol/"

  [[menu.main]]
    identifier = "paracosm"
    name       = "Paracosm"
    url        = "/paracosm/"

  [[menu.main]]
    identifier = "apostrophe"
    name       = "Apostrophe"
    url        = "/apostrophe/"

  [[menu.main]]
    identifier = "looking-glass"
    name       = "üîç Looking Glass"
    url        = "/looking-glass/"

  [[menu.main]]
    identifier = "ii"
    name       = "Imaginary Interpreter"
    url        = "/ii/"

  [[menu.main]]
    identifier = "cterm"
    name       = "Complex Term"
    url        = "/cterm/"

  [[menu.main]]
    identifier = "ink"
    name       = "Ink.el"
    url        = "/ink/"

  [[menu.main]]
    identifier = "examplary"
    name       = "Examplary"
    url        = "/examplary/"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts/"