#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/semiosis/semiosis-hugo
#+HUGO_SECTION: ./posts

#+TITLE: Beyond the boundaries of paradigms
#+DATE: <2021-09-07>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: gpt blockchain language

** Examples of ordinary programming paradigms
- Type-Level programming
  - https://rebeccaskinner.net/posts/2021-08-25-introduction-to-type-level-programming.html
- Relational Programming
  - https://github.com/webyrd/dissertation-single-spaced/blob/master/thesis.pdf
- Functional programming
- Object-oriented programming
- Imperative programming

** Questions to ponder
- Where do ordinary programming paradigms end and what exists between and beyond them?
- Do there exist boundaries between physical, imaginary and metaphysical languages?
- What constitutes a new paradigm in programming?
  Arguably something that is orthogonal or unique to the rest.
- May Imaginary Programming (IP) be considered a new programming paradigm?
  - I think it can be.
- Is the past mutable?
  - I think it's possible. If one makes their reality a
    a simulation of the future then they may
    change the past.
  - But is it far enough to send a message 30+ years?
  - Metaphysical language?

** Hierarchy of languages
- Physical languages
  - Zoösemiosis
- Imaginary languages
  - World languages
    - English
    - Japanese
    - Sign language
  - Natural languages
    - Non-verbal body language
  - Formal languages
    - Markdown
    - C++
- Metaphysical languages
  - Intellectual without cognitive materials

*** Explanation
Imaginary is like [a representation of] the superset of these types of languages, mathematically but also imaginarily 
by a neural network, but perhaps also by people.
Machine analogs serve as a good tool for thought and comparison when contemplating the nature of reality though.
Physical languages would be sort of hard-wired into reality; There's no intellectual (understanding) component, only sense.

https://muse.jhu.edu/article/636617/summary

Metaphysical languages would transcend the physical and exist only in understanding; It's beyond mechanical sensory perception.
(or something like that. will see how it goes.)

** Mutable past
It's easy to imagine though that if you make
your base reality a simulation, then you have
the ability to change the past based on
physical languages that are programmed into
your reality as triggers, if that makes sense?
I think that there doesnt have to be such a
strong boundary between virtual present and
past though. For example Jeff Bezos plans 5
years ahead. Perhaps to optimise, me may
support his thought processes with AI to push
more of his thought into a simulated future
reality. Then he has the ability to act in
the present to change situations, effectively
changing his virtual past.

Regardless, in light of LMs and neural nets, I
think it's important to build a virtual
reality for yourself that's based on
simulation of the future? To relegate yourself
to the reality that has been created for you
via recommendation algorithms and the effects
of AI (i.e. to relegate yourself to live only
in the present) means you are missing out on
something, which is the very real power that
comes from using the AI's to infer the future
and to be able to act on information gathered
that way.

** Thoughts on Imaginary Programming
The fundamental theorem of algebra states that
every non-constant single-variable polynomial
with complex coefficients has at least one
complex root.

The fundamental theorem of algebra implies that
solutions to polynomials are only available
when adding the imaginary dimension.

Likewise, solutions to problems such as
translating between world languages require
the addition of multiple dimensions.

Historically, words and phrases may be
modelled by a vector space of 200 dimensions,
i.e. FastText.

Nowadays we use tensors which are n-ranked
matrices that lazily yield their values (i.e.
sparse matrix optimisation, and TF optimises
out computation of the values in tensor
cells).

However, like the Bohr model of the atom, an
n-dimensional vector-space is a useful
concept.

Large LMs such as GPT-X are a representation
of a superset of languages, the languages of
the data they are trained on.

** Speculation of LMs of the future
They may serve as snapshots of a given time
period, and may be used to generatively
recreate experiences from the time they were
created.

#+BEGIN_SRC text -n :async :results verbatim code
  synchronic
      Concerned with something, especially a
      language, as it exists at one point in
      time.
      "synchronic linguistics"
#+END_SRC

These may be recorded on blockchain. Post-
human ocean marketplace perhaps.

For example, GPT-3 may one day be used to re-
create YouTube via simulation.

I think it's rather obvious that the world is
heading for building simulations of the
internet within LMs.

My worry is that corporations with too much
power, or nation states will leverage their
LMs to create information bubbles which are
increasingly difficult to escape from, and
traverse between.

** Synchronic links
+ Messages backwards in time :: https://youtu.be/I9y62qoTsic?t=978