#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/semiosis/semiosis-hugo
#+HUGO_SECTION: ./posts

#+TITLE: Beyond the boundaries of paradigms
#+DATE: <2021-09-07>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: gpt blockchain

** Beyond the boundaries of paradigms

Questions to ponder:
- Where do regular programming paradigms end?
- How do you connect one language to the next?

What constitutes a new paradigm? Arguably something that is orthogonal to the
rest. May Imaginary Programming (IP) be considered a new programming paradigm?

Hierarchy of languages:
- Imaginary languages
  - World languages
    - English
    - Japanese
  - Natural languages
    - Sign language
    - Non-verbal body language
  - Formal languages
    - Markdown
    - C++

- The fundamental theorem of algebra
  - Solutions to polynomials only available when adding the imaginary dimension

Likewise, solutions to problems such as
translating between world languages requires
the addition of multiple dimensions.

Historically, words and phrases may be
modelled by a vector space of 200 dimensions,
i.e. FastText.

Nowadays we use tensors which are n-ranked
matrices that lazily yield their values (i.e.
sparse matrix optimisation, and TF optimises
out computation of the values in tensor
cells).

However, like the Bohr model of the atom, an
n-dimensional vector-space is a useful
concept.

Large LMs such as GPT-X are a representation
of a superset of languages, the languages of
the data they are trained on.

They may serve as snapshots of a given time
period, and may be used to generatively
recreate experiences from the time they were
created.

For example, GPT-3 may one day be used to re-
create YouTube via simulation.