#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/semiosis/semiosis-hugo
#+HUGO_SECTION: ./posts

#+TITLE: EmacsConf 2021 - Imaginary Programming
#+DATE: <2021-09-05>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: imaginary-programming gpt emacs imaginary 位

* Talk: _Imaginary Programming_

+ video :: https://www.youtube.com/watch?v=yuSPO6xwwu8
+ slides :: [[https://github.com/mullikine/imaginary-programming-transcript-emacsconf-2021/blob/master/presentation.pdf][presentation.pdf]]

** Abstract:
Imaginary Programming (=IP=) is both methodology and paradigm. It is an extension
of literate programming and a way of creating software without the use of
imperative, functional or even declarative code. Yet IP employs all disciplines
to achieve the miraculous. The only contingency is on one or more language
models, known as foundation models. The real value of IP is not
found by abandoning sound logic altogether, but in weaving the real with the
imaginary. The future of imaginary programming is one in which almost all of
computing is inferred. I have built a suite of tools based on emacs for
interfacing real programming languages with imaginary ones; all of this in
order to demonstrate what I mean; a 'complex' terminal that lets you imagine
what happens no matter how nested you are within interpreters, an example-oriented
language, a file format that encodes the provenance of text and a library for
imaginary functional programming primitives called iLambda. It is important to
recognise IP because, for lack of a better term, it has far-reaching implications for
intellectual property and the GPL. Please keep an open mind.

** Outlines:
- 5-10 minutes:
    - a 5 minute introduction to imaginary programming, followed by
    - a demonstration of iLambda.
      - [[https://mullikine.github.io/posts/designing-an-imaginary-programming-ip-library-for-emacs/][i位, a family of imaginary programming libraries]]

- 20 minutes:
    - a 5 minute introduction to imaginary programming, followed by
    - a 5 minute introduction and demonstration of Pen.el.
      - https://semiosis.github.io/pen/
    - a 5 minute org-babel and emacs lisp demonstration of iLambda.
      - [[https://mullikine.github.io/posts/designing-an-imaginary-programming-ip-library-for-emacs/][i位, a family of imaginary programming libraries]]
    - a 5 minute demonstration of 'cterm' (complex term) and 'ii' (imaginary interpreter).
      - https://mullikine.github.io/posts/imaginary-real-codex-complex/
      - https://semiosis.github.io/ii/
      
- 40 minutes:
    - a 10 minute introduction to language models, their capabilities and imaginary programming.
    - a 10 minute introduction to creating prompts with Pen.el.
    - a 5 minute org-babel and emacs lisp demonstration of iLambda.
      - [[https://mullikine.github.io/posts/designing-an-imaginary-programming-ip-library-for-emacs/][i位, a family of imaginary programming libraries]]
    - a 5 minute demonstration of 'cterm' (complex term) and 'ii' (imaginary interpreter).
      - https://mullikine.github.io/posts/imaginary-real-codex-complex/
      - https://semiosis.github.io/ii/
    - A 5 minute brief on examplary and advanced prompt programming.
      - https://semiosis.github.io/examplary/
    - 5 minutes for Prompting Requests and Q&A

** Availability
(during the conference days (Nov 27 and 28))

All hours.

** How you'd like to handle questions
*** Live web conference
+ IRC :: =libertyprime= at =#emacs= on =libera=