#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/semiosis/semiosis-hugo
#+HUGO_SECTION: ./posts

#+TITLE: Exploring Neuralink concepts with GPT-3
#+DATE: <2021-04-14>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: GPT-3 neuralink neuroengineering

** Summary
I create several =org-brain= repositories for
exploratory learning and ideation.

#+BEGIN_SRC text -n :async :results verbatim code
  billboard
  exploratory
  fungible
  ideation
  infogetics
  infrastructure-tooling
  neuralink
  open-source-alternatives
  reference
  thoughts
  tooling
  welfare-organisations
#+END_SRC

I then use GPT-3 to discuss topics and why they are important.

** Glossaries
+ http://github.com/mullikine/glossaries-gh/blob/master/biochemistry.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/brain-computer-interface-bci.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/neuralink.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/neuroscience.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/neural-engineering.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/gpt.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/ai-safety.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/general-ai-agi.txt

** Demonstration
Future of life institute and telepathy.

#+BEGIN_EXPORT html
<!-- Play on asciinema.com -->
<!-- <a title="asciinema recording" href="https://asciinema.org/a/gNHRbCi7kQDT6qFRih1zvLyni" target="_blank"><img alt="asciinema recording" src="https://asciinema.org/a/gNHRbCi7kQDT6qFRih1zvLyni.svg" /></a> -->
<!-- Play on the blog -->
<script src="https://asciinema.org/a/gNHRbCi7kQDT6qFRih1zvLyni.js" id="asciicast-gNHRbCi7kQDT6qFRih1zvLyni" async></script>
#+END_EXPORT

*** What is =neuroengineering=?

#+BEGIN_EXPORT html
<!-- Play on asciinema.com -->
<!-- <a title="asciinema recording" href="https://asciinema.org/a/xs8YGxIbCZ4Bpc85N2qhenoRb" target="_blank"><img alt="asciinema recording" src="https://asciinema.org/a/xs8YGxIbCZ4Bpc85N2qhenoRb.svg" /></a> -->
<!-- Play on the blog -->
<script src="https://asciinema.org/a/xs8YGxIbCZ4Bpc85N2qhenoRb.js" id="asciicast-xs8YGxIbCZ4Bpc85N2qhenoRb" async></script>
#+END_EXPORT

** Scrape the neuralink website for youtube videos
#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  cd "$DUMP/programs/httrack/mirrors/-r6-https-neuralink-com-"
  anygrep rosie-urls | grep youtube.com | oc -u | pavs
#+END_SRC

#+NAME: neuralink-website-vids
#+RESULTS:
#+begin_src bash
[[https://www.youtube.com/watch?v=DVvmgjBL74w][Neuralink Progress Update, Summer 2020 - YouTube]]
[[https://www.youtube.com/watch?v=rsCul1sp4hQ][Monkey MindPong - YouTube]]
[[https://www.youtube.com/watch?v=iSutodqCZ74][Snout Boops - YouTube]]
[[https://www.youtube.com/watch?v=LgJpYOTll8U][Monkey MindPong Picture-in-Picture - YouTube]]
[[https://www.youtube.com/watch?v=gMCkMHbpPFA][Animal Care at Neuralink - YouTube]]
[[https://www.youtube.com/watch?v=-gQn-evdsAo][Working on the Neuralink Robot - YouTube]]
#+end_src

** TODO Generate transcripts
$MYGIT/semiosis/prompts/prompts/key-points.prompt

#+BEGIN_EXPORT html
<!-- Play on asciinema.com -->
<!-- <a title="asciinema recording" href="https://asciinema.org/a/NNGjEYHB9B2rOyvUAPzMPI0sa" target="_blank"><img alt="asciinema recording" src="https://asciinema.org/a/NNGjEYHB9B2rOyvUAPzMPI0sa.svg" /></a> -->
<!-- Play on the blog -->
<script src="https://asciinema.org/a/NNGjEYHB9B2rOyvUAPzMPI0sa.js" id="asciicast-NNGjEYHB9B2rOyvUAPzMPI0sa" async></script>
#+END_EXPORT

*** [[https://www.youtube.com/watch?v=DVvmgjBL74w][Neuralink Progress Update, Summer 2020 - YouTube]]
$DUMP/tmp/scratchF4ZkzB.txt

*** [[https://www.youtube.com/watch?v=rsCul1sp4hQ][Monkey MindPong - YouTube]]
+ Transcript :: [[./monkey-mindpong.txt]]

This is Pager.

He's a nine-year-old macaque who had a
neurolink placed in each side of his brain
about six weeks ago.

If you look carefully, you can see that the
fur on his head hasn't quite fully grown back
yet.

He's learnt to interact with a computer for a
tasty banana smoothie delivered through a
straw.

We can interact with the neurolinks simply by
pairing them to an iPhone, just as you might
pair your phone to a Bluetooth speaker.

The links record from more than 2000
electrodes implanted in the regions of the
subject's motor cortex that coordinate hand
and arm movements.

Neurons in this region modulate their activity
with intended hand movement for example, some
might become more active when the subject
moves his hand up, and others when he moves it
to the right.

*** [[https://www.youtube.com/watch?v=iSutodqCZ74][Snout Boops - YouTube]]

*** [[https://www.youtube.com/watch?v=LgJpYOTll8U][Monkey MindPong Picture-in-Picture - YouTube]]

*** [[https://www.youtube.com/watch?v=gMCkMHbpPFA][Animal Care at Neuralink - YouTube]]

*** [[https://www.youtube.com/watch?v=-gQn-evdsAo][Working on the Neuralink Robot - YouTube]]
