#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/semiosis/semiosis-hugo
#+HUGO_SECTION: ./posts

#+TITLE: Exploring Neuralink concepts with GPT-3 (WIP)
#+DATE: <2021-04-14>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: GPT-3 neuralink neuroengineering

_/This article is a work in progress./_

** Summary

I create several =org-brain= repositories for
exploratory learning and ideation.

#+BEGIN_SRC text -n :async :results verbatim code
  billboard
  exploratory
  fungible
  ideation
  infogetics
  infrastructure-tooling
  neuralink
  open-source-alternatives
  reference
  thoughts
  tooling
  welfare-organisations
#+END_SRC

I then use GPT-3 to discuss topics and why they are important.

** Glossaries
+ http://github.com/mullikine/glossaries-gh/blob/master/biochemistry.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/brain-computer-interface-bci.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/neuralink.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/neuroscience.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/neural-engineering.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/gpt.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/ai-safety.txt
+ http://github.com/mullikine/glossaries-gh/blob/master/general-ai-agi.txt

** Demonstration
Future of life institute and telepathy.

#+BEGIN_EXPORT html
<!-- Play on asciinema.com -->
<!-- <a title="asciinema recording" href="https://asciinema.org/a/gNHRbCi7kQDT6qFRih1zvLyni" target="_blank"><img alt="asciinema recording" src="https://asciinema.org/a/gNHRbCi7kQDT6qFRih1zvLyni.svg" /></a> -->
<!-- Play on the blog -->
<script src="https://asciinema.org/a/gNHRbCi7kQDT6qFRih1zvLyni.js" id="asciicast-gNHRbCi7kQDT6qFRih1zvLyni" async></script>
#+END_EXPORT

*** What is =neuroengineering=?

#+BEGIN_EXPORT html
<!-- Play on asciinema.com -->
<!-- <a title="asciinema recording" href="https://asciinema.org/a/xs8YGxIbCZ4Bpc85N2qhenoRb" target="_blank"><img alt="asciinema recording" src="https://asciinema.org/a/xs8YGxIbCZ4Bpc85N2qhenoRb.svg" /></a> -->
<!-- Play on the blog -->
<script src="https://asciinema.org/a/xs8YGxIbCZ4Bpc85N2qhenoRb.js" id="asciicast-xs8YGxIbCZ4Bpc85N2qhenoRb" async></script>
#+END_EXPORT

** A paper from my professor Zhiyi Huang
https://link.springer.com/article/10.1007%2Fs13755-021-00142-y

*** New terms taken from the synopsis
#+BEGIN_SRC text -n :async :results verbatim code
  Crosstalk
      Unintended brain activations that
      interfere with bimanual actions and could
      also occur during motor imagery.

  Bimanual coordination
      Encompasses a large class of situations in
      which the brain must simultaneously
      control multiple movements, such as when
      we use our two hands to manipulate an
      object or perform a task.

      Bimanual coordination has been one of the
      most widely studied problems in motor
      control.

  Pairwise classification
      A class binarization procedure that
      converts a multi-class problem into a
      series of two-class problems, one problem
      for each pair of classes.

  Motor imagery
      A dynamic state during which an individual
      mentally simulates a physical action.

      This type of phenomenal experience implies
      that the subject feels themselves
      performing the action.
#+END_SRC

*** Synopsis (tidied)
Brain–computer interfaces (BCIs) target
specific brain activity for neuropsychological
rehabilitation, and also allow patients with
motor disabilities to control mobility and
communication devices.

Motor imagery of single-handed actions is used
in BCIs but many users cannot control the BCIs
effectively, limiting applications in the
health systems.

Crosstalk is unintended brain activations that
interfere with bimanual actions and could also
occur during motor imagery.

To test if crosstalk impaired BCI user
performance, we recorded EEG in 46
participants while they imagined movements in
four experimental conditions using motor
imagery: left hand (L), right hand (R), tongue
(T) and feet (F).

Pairwise classification accuracies of the
tasks were compared (LR, LF, LT, RF, RT, FT),
using common spatio-spectral filters and
linear discriminant analysis.

We hypothesized that LR classification
accuracy would be lower than every other
combination that included a hand imagery due
to crosstalk.

As predicted, classification accuracy for LR
(58%) was reliably the lowest.

Interestingly, participants who showed poor LR
classification also demonstrated at least one
good TR, TL, FR or FL classification; and good
LR classification was detected in 16% of the
participants.

For the first time, we showed that crosstalk
occurred in motor imagery, and affected BCI
performance negatively.

Such effects are effector-sensitive regardless
of the BCI methods used; and likely not
apparent to the user or the BCI developer.

This means that tasks choice is crucial when
designing BCI.

Critically, the effects of crosstalk appear
mitigatable.

We conclude that understanding crosstalk
mitigation is important for improving BCI
applicability.

** Scrape the neuralink website for youtube videos
#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  cd "$DUMP/programs/httrack/mirrors/-r6-https-neuralink-com-"
  anygrep rosie-urls | grep youtube.com | oc -u | pavs
#+END_SRC

#+NAME: neuralink-website-vids
#+RESULTS:
#+begin_src bash
[[https://www.youtube.com/watch?v=DVvmgjBL74w][Neuralink Progress Update, Summer 2020 - YouTube]]
[[https://www.youtube.com/watch?v=rsCul1sp4hQ][Monkey MindPong - YouTube]]
[[https://www.youtube.com/watch?v=iSutodqCZ74][Snout Boops - YouTube]]
[[https://www.youtube.com/watch?v=LgJpYOTll8U][Monkey MindPong Picture-in-Picture - YouTube]]
[[https://www.youtube.com/watch?v=gMCkMHbpPFA][Animal Care at Neuralink - YouTube]]
[[https://www.youtube.com/watch?v=-gQn-evdsAo][Working on the Neuralink Robot - YouTube]]
#+end_src

** TODO Generate transcripts
$MYGIT/semiosis/prompts/prompts/key-points.prompt

#+BEGIN_EXPORT html
<!-- Play on asciinema.com -->
<!-- <a title="asciinema recording" href="https://asciinema.org/a/NNGjEYHB9B2rOyvUAPzMPI0sa" target="_blank"><img alt="asciinema recording" src="https://asciinema.org/a/NNGjEYHB9B2rOyvUAPzMPI0sa.svg" /></a> -->
<!-- Play on the blog -->
<script src="https://asciinema.org/a/NNGjEYHB9B2rOyvUAPzMPI0sa.js" id="asciicast-NNGjEYHB9B2rOyvUAPzMPI0sa" async></script>
#+END_EXPORT

*** [[https://www.youtube.com/watch?v=rzNOuJIzk2E][Neuralink Monkey MindPong Deconstructed - YouTube]]
[[./monkey-mindpong-deconstructed.txt]]

*** [[https://www.youtube.com/watch?v=DVvmgjBL74w][Neuralink Progress Update, Summer 2020 - YouTube]]
[[./neuralink-progress-summer2020.txt]]

*** [[https://www.youtube.com/watch?v=rsCul1sp4hQ][Monkey MindPong - YouTube]]
+ Transcript :: [[./monkey-mindpong.txt]]

This is Pager.

He's a nine-year-old macaque who had a
neurolink placed in each side of his brain
about six weeks ago.

If you look carefully, you can see that the
fur on his head hasn't quite fully grown back
yet.

He's learnt to interact with a computer for a
tasty banana smoothie delivered through a
straw.

We can interact with the neurolinks simply by
pairing them to an iPhone, just as you might
pair your phone to a Bluetooth speaker.

The links record from more than 2000
electrodes implanted in the regions of the
subject's motor cortex that coordinate hand
and arm movements.

Neurons in this region modulate their activity
with intended hand movement for example, some
might become more active when the subject
moves his hand up, and others when he moves it
to the right.

*** [[https://www.youtube.com/watch?v=iSutodqCZ74][Snout Boops - YouTube]]

*** [[https://www.youtube.com/watch?v=LgJpYOTll8U][Monkey MindPong Picture-in-Picture - YouTube]]

*** [[https://www.youtube.com/watch?v=gMCkMHbpPFA][Animal Care at Neuralink - YouTube]]

*** [[https://www.youtube.com/watch?v=-gQn-evdsAo][Working on the Neuralink Robot - YouTube]]
