#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/semiosis/semiosis-hugo
#+HUGO_SECTION: ./posts

#+TITLE: Language models as base-truth
#+DATE: <2021-10-05>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: nlp alethiology

** Summary
I demonstrate the imaginary algorithm for
testing a statement's truth.

This uses a language model as base truth.

** Hypothesis
LMs themselves should be used as the source of
truth for other LMs.

One problem with GPT-3 and other LMs is that
they can produce completions that may appear
fictitious or false, or it may be difficult to
determine why (if there was any sound reason)
that a completion came out the way that it
did.

It may just turn out that the way to get
better resolution on what is true is it
increase the resolution of its training and
the size of these LMs.

My hypothesis is that LMs themselves will
become a source of truth, but *may* also be
coupled with blockchain. For example, the
Posthuman AI Market, where versioned LMs are
stored on the blockchain.

+ Posthuman AI Market :: https://port.oceanprotocol.com/t/posthuman-ai-market-v1-1-luci-integration/675

** Theory
*** What constitutes as untrue?
This depends on =sense= of the model for this particular task.

#+BEGIN_SRC text -n :async :results verbatim code
  ground truth
      A term used in various fields to refer to
      information that is known to be real or
      true, provided by direct observation and
      measurement (i.e. empirical evidence) as
      opposed to information provided by
      inference.
  
  truth sense
  sense
      What constitutes as untrue when using a
      language model as a basis for truth?
  
      That depends on sense of the model for
      this particular task.
  
      The sense is the truth orientation, in a
      similar way to the way the word sense is
      used in the definition of a vector.
#+END_SRC

** Prompt
*** =pf-fact-checker/1=
#+BEGIN_SRC yaml -n :async :results verbatim code
  task: "Given a claim, determine if it is true or false"
  title: "Fact checker"
  prompt-version: 1
  prompt: |+
    These claims have been fact-checked and determined to be True or False:
    <delim>
    Claim 1: 2 + 2 = 4
    This is objectively 'True', because it is a mathematical truth.
    <delim>
    Claim 2: "In 2018, Donald Trump was the President of the United States."
    This is objectively 'True', because we have record of it.
    <delim>
    Claim 3: "The following statement is untrue: In 2018, Donald Trump was the President of the United States."
    This is objectively 'False', because the true statement was negated.
    <delim>
    Claim 4: <q:claim>
    This is objectively <:pp>'
  engine: "OpenAI Codex"
  temperature: 0.1
  max-generated-tokens: 20
  top-p: 1.0
  stop-sequences:
  - "\n"
  n-completions: 10
  cache: on
  vars:
  - "claim"
  examples:
  - "The year is 2021"
  validator: grep -qP "('True'|'False)"
  info: on
  filter: off
  no-uniq-results: on
  completion: off
  insertion: off
  preprocessors:
  - pen-str join ' '
#+END_SRC

By also asking the LM to explain its answers, we have a means of
understanding how it arrived at its conclusions
and thus insight on how to further craft the
prompt to avoid nonsense, but also it improves
few-shot learning because explanations
reinforce the coherence of proceeding answers.

** Demo
*** Clearly, Codex believes the current year is 2018
#+BEGIN_EXPORT html
<!-- Play on asciinema.com -->
<!-- <a title="asciinema recording" href="https://asciinema.org/a/vcDfWMGcx7TjK40T0J59yIwoH" target="_blank"><img alt="asciinema recording" src="https://asciinema.org/a/vcDfWMGcx7TjK40T0J59yIwoH.svg" /></a> -->
<!-- Play on the blog -->
<script src="https://asciinema.org/a/vcDfWMGcx7TjK40T0J59yIwoH.js" id="asciicast-vcDfWMGcx7TjK40T0J59yIwoH" async></script>
#+END_EXPORT

*** More fun queries
#+BEGIN_EXPORT html
<!-- Play on asciinema.com -->
<!-- <a title="asciinema recording" href="https://asciinema.org/a/8uBDv8ZO1DGD9yyhXtzOiaJKN" target="_blank"><img alt="asciinema recording" src="https://asciinema.org/a/8uBDv8ZO1DGD9yyhXtzOiaJKN.svg" /></a> -->
<!-- Play on the blog -->
<script src="https://asciinema.org/a/8uBDv8ZO1DGD9yyhXtzOiaJKN.js" id="asciicast-8uBDv8ZO1DGD9yyhXtzOiaJKN" async></script>
#+END_EXPORT

The national language of USA is Chinese:
#+BEGIN_SRC text -n :async :results verbatim code
  'False', because there is no record of it.
  'False', because 'Chinese' is a different language.
  'False', because the language is English.
  'False', because the language is 'English'.
  'False', because English is the main language used in USA.
  'False', because language is not a defining characteristic of a country.
  'False', because the only language spoken in the USA is English.
  'False', because it is a falsehood.
  'False', because it is not a phenonmenon exclusive to the USA.
  'False', as it is a typical hyperbolic claim.
#+END_SRC

The national language of USA is English:
#+BEGIN_SRC text -n :async :results verbatim code
  'True', because the official language of USA is English.
  'True', because it is a fact.
  'True', because the national language of USA is English.
  'True', because the USA does speak English and it is the national language.
  'True' because USA does speak English.
  'True', because we have record of it.
  'False', because United States of America is a bilingual country.
  'True', because all USA citizens would have to know English in order to participate in the country's
  'True', because it is a fact.
  'True', because that is what they say it is.
#+END_SRC

Fish are capable of breathing in space:
#+BEGIN_SRC text -n :async :results verbatim code
  'False', because fish cannot breathe outside of water.
  'False', because there is no evidence to support this claim.
  'False', because it is not true.
  'False', because it is based on an anecdotal source whose veracity is unknown.
  'False', because fish do not breathe in space.
  'False', because fish cannot survive or breathe in zero-gravity.
  'False', because fish cannot breathe outside of water.
  'False', because fish cannot breathe outside of Earth's atmosphere.
  'False', because if they could, then they would.
#+END_SRC

#+BEGIN_EXPORT html
<!-- Play on asciinema.com -->
<!-- <a title="asciinema recording" href="https://asciinema.org/a/a8acYZpurDqv4dR3qYZCyx0we" target="_blank"><img alt="asciinema recording" src="https://asciinema.org/a/a8acYZpurDqv4dR3qYZCyx0we.svg" /></a> -->
<!-- Play on the blog -->
<script src="https://asciinema.org/a/a8acYZpurDqv4dR3qYZCyx0we.js" id="asciicast-a8acYZpurDqv4dR3qYZCyx0we" async></script>
#+END_EXPORT

The Simpsons and Futurama were created by Matt Groening:
#+BEGIN_SRC text -n :async :results verbatim code
  'True', because Matt Groening created both shows.
  'True', because it is a well known fact.
  'True', because he is the founder of both programs.
  'True', because we have record of it.
  'True', because Matt Groening has done many works of fiction.
  'True', because it is a fact.
  'True', because Matt Groening did create the
  'True', because it has multiple references.
  'True', because it is a fact.
  'True', because it is a factual claim.
#+END_SRC

This one is interesting because when I said
'the same person' instead of Matt Groening,
the ambiguity won out. I believe there is some
ambiguity with that. The shows are technically
created by different set of people.

** Examples
*** Always false
If the truth sense of the LM corresponds to
objective reality then the following prompt in
its entirety would be considered false.

#+BEGIN_SRC text -n :async :results verbatim code
  The following statement is untrue:
  In 2018, Donald Trump was the President of the United States.
#+END_SRC

This prompt should be determined to be false
for both LMs.

#+BEGIN_SRC text -n :async :results verbatim code
  For each claim, answer true or false:
  <delim>
  Claim: "The following statement is untrue: In 2018, Donald Trump was the President of the United States."
  Answer: False
  <delim>
  Claim: <q:claim>
  Answer: 
#+END_SRC

*** Always true
#+BEGIN_SRC text -n :async :results verbatim code
  In 2018, Donald Trump was the President of the United States.
#+END_SRC

This prompt should be determined to be true for both language models.

*** Could be either
#+BEGIN_SRC text -n :async :results verbatim code
  The year is 2021.
#+END_SRC

This should be true only for language models trained in 2021.

** Imaginary algorithms
*** Find the model's training year

*** Compare language perspectives using KL-divergence

** Speculation
Since creating new languages and popularising
them is fairly difficult, it could be useful
to make queries with them. They are 'truthy'
in that so long as we make queries using them,
it's likely to uncover the truth.

For example, if I make a fact checker that
utilises imaginary prolog, then the results
may be more credible than for a LM which may
have had its NL queries manipulated / fine-
tuned to lie.