#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/semiosis/semiosis-hugo
#+HUGO_SECTION: ./posts

#+TITLE: Pen.el host interop and client/server
#+DATE: <2021-07-29>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: gpt emacs nlp docker pen

** Summary
=Pen.el= may now run as a server.
On your host OS, you can create symlinks to the =pen= script
with names matching the name of prompts.
Running those symlinks will then run the prompt
via the server and return the result.

Alternatively, you can run =pen pf-my-prompt-function "first arg" "second arg" "etc."= on
the host machine and it will run the prompt
function on the server and return the output
as stdout on the host.

You can even pipe into =pen= or the symlinks
and the stdin will be used as the first
argument to the prompt.

This means it is now dead simple
to integrate GPT-3 and other LMs easily into
your bash pipelines and other software. =Pen.el=
is now your management system for LMs and
prompting.

You may create multiple client interfaces to =Pen.el=,
which means you can have many prompt-engineering workflows going at once.

You may want to be working with multiple
documents, for example, or have a separate
client just for prompt engineering.

+ GitHub project :: [[https://github.com/semiosis/pen.el/][GitHub - semiosis/pen.el: pen.el is a package for prompt engineering in emacs. It facilitates the creation, ongoing development, discovery and usage of prompts to a language model such as OpenAI's GPT-3 or EleutherAI's GPT-j.]]

+ Project timeline and objectives :: https://github.com/semiosis/pen.el/tree/master/docs

+ Prompt README :: [[http://github.com/semiosis/prompts/blob/master/README.org][prompts/README.org at master  semiosis/prompts  GitHub]]

+ Tutorial :: https://semiosis.github.io/posts/pen-tutorial/

+ Video demo of =Pen.el= : [[https://www.youtube.com/watch?v=J9BnZjWV1jw][Augment Minds 2021: Demo of Loom and Pen.el - YouTube]]

** Running a prompt function from the host
*** Firstly, start a server
#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  pen
#+END_SRC

To run additional clients, just run =pen=
again in a different terminal.

*** Then run a prompt function
#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  pen -e '(car (pf-list-of 5 "tennis players" :no-select-result t))'
#+END_SRC

#+RESULTS:
#+begin_src bash
Elena Dementieva
Roger Federer
Marat Safin
Anastasia Myskina
Andre Agassi
#+end_src

*** Alternatively, make a symlink to the =pen= script
Like so:
#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  ln -sf pen pf-list-of
#+END_SRC

Then you may run the functions as scripts on your host.
#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  pf-list-of 5 "tennis players"
#+END_SRC

#+RESULTS:
#+begin_src bash
Elena Dementieva
Roger Federer
Marat Safin
Anastasia Myskina
Andre Agassi
#+end_src

#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  echo "How shave a beard" | pen pf-complicated-explanation-of-how-to-x
#+END_SRC

#+RESULTS:
#+begin_src bash
A beard is the collection of coarse hair that
grows on the chin and cheeks of humans and
some non-human animals. The term is often used
to describe acollection of hair that forms on
the chin and cheeks of humans, and to a lesser
extent on the face of some male monkeys.
Depending on the context, the term might refer
to the hair on the chin or to the collection
of hair on the lower face. In the English
language the term beard also refers to the
hair that grows on the
#+end_src

#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  echo "How to crack an egg" | pen pf-complicated-explanation-of-how-to-x
#+END_SRC

#+RESULTS:
#+begin_src bash
Cracking an egg involves application of force
sufficient to cause the eggshell to separate
from the egg white and the egg yolk. The
eggshell is composed of calcium carbonate
which is soluble in dilute hydrochloric acid.
Solution of calcium carbonate is achieved by
application of heat. The application of heat
is achieved by creating a temperature gradient
between the egg and the egg receptacle. The
egg receptacle is composed of ceramic
materials which are highly resistant to
thermal shock. Cracking the egg results
#+end_src

=Pen.el= saves the outputs of prompt functions
by default, so extending the command as below
will reuse the same output.

#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  echo "How to crack an egg" | pen pf-complicated-explanation-of-how-to-x | pen pf-tldr-summarization
#+END_SRC

#+RESULTS:
#+begin_src bash
I cracked an egg on a ceramic plate and the eggshell separated from the egg white and yolk.
#+end_src

#+BEGIN_SRC bash -n :i bash :async :results verbatim code
  pf-very-witty-pick-up-lines-for-a-topic egypt
#+END_SRC

#+RESULTS:
#+begin_src bash
I wonder if the pyramids would've still been built if the Egyptians had Tinder?
Did you know, in Egypt, cats are considered to be good luck?
I'm in Egypt, looking for some artefacts.
Are you Cleopatra? Because I want you to be my Queen.
My heart says mummies, but my body says pyramids.
You look like pharaoh material.
I want to be the one you wake up to in the morning.
Your sarcophagus would be mine.
I want to make you my pyramid.
I want to be where the Nile flows.
Have you ever been to Egypt? I don't think it's the pyramids, I think it's you.
You look like Cleopatra reincarnated.
Let's spend a day in Egypt.
Do you like Egyptian men? Cuz I like Egyptian women even though they don't exist.
Hey, I'm Tut, you're my Ka, I guess that makes you my cat.
You look like the type that would be found in the Valley of the Kings.
Your body is like the pyramids. Uncovering you would be a true archeological find.
I want to build a pyramid. With you. Inside you.
If you were a pharaoh I would build you a pyramid.
Do you want to be queen of my Nile?
#+end_src

** Demo
#+BEGIN_EXPORT html
<!-- Play on asciinema.com -->
<!-- <a title="asciinema recording" href="https://asciinema.org/a/dw0c0VueMHC8NOvGHmEgUUDcr" target="_blank"><img alt="asciinema recording" src="https://asciinema.org/a/dw0c0VueMHC8NOvGHmEgUUDcr.svg" /></a> -->
<!-- Play on the blog -->
<script src="https://asciinema.org/a/dw0c0VueMHC8NOvGHmEgUUDcr.js" id="asciicast-dw0c0VueMHC8NOvGHmEgUUDcr" async></script>
#+END_EXPORT