K#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/semiosis/semiosis-hugo
#+HUGO_SECTION: ./posts

#+TITLE: Spiritual Mysteries
#+DATE: <2021-09-20>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: faith

** Relevant links
+ YouTube vid :: [[https://www.youtube.com/watch?v=0X6xFMRrLGY][Spiritual Warfare by Billy Graham Crusade Phoenix, AZ 1974 - YouTube]]

+ Subtitles :: [[./billy-graham-subs.txt]]

** Summary
In recent times I have been confronted with a
bit of an ontological crisis.

Normal life and social rules cease to delude
me now with its doctrine of right and wrong
and cease to have an oppressing hold on my
life.

However, through new eyes, and being somebody
who interprets and seeks meaning, and to
derive meaning in the things that I do, I now
have to ascribe events, circumstances and
incongruencies with explanation.

Lies that are prevalent may oppress and
prevent a person from glorifying and honoring
God. Because God created us with a telos; a
purpose. A seed grows into a flower, but for
what purpose? What is the purpose of a person?
Certainly not to hide within their shell,
unable to bravely confront what they believe
is true and imprint that truth upon the world.

For instance, God created us with unique gifts
and purposes but there is a thick veil of lies
(mainly intellectual) that a person has to
fight through, and until then believes about
themselves. Those lies will actually prevent
them from performing even the smallest of
steps towards freedom, and will twist good
things into bad things.

Near the beginning of 2021 I have encountered
my greatest fear. Against everybody around me
-- not a single soul would encourage me. I've
continued on that path. I could only do it
with a strong belief in God's validation.
There was a single moment and afterwards, my
heart went from twisted and in pain to a
feeling of being at least twice the size and
utterly rushing with the feeling of being
loved, and my life from stagnant an inhibited
to a feeling of endless freedom and
exploration of things beyond this fictional
and invisible wall.

Lies oppress and control, they destroy and
lead to death; spiritual, mental and physical.

This is what Billy Graham is talking about in
the video when he says:
#+BEGIN_SRC text -n :async :results verbatim code
  "He promises freedom liberty and life but he
  produces only sorrow, slavery and death. He's
  a deceiver."
#+END_SRC

** Bible Passages
#+BEGIN_SRC text -n :async :results verbatim code
  Deuteronomy 18:10-11
  New International Version
  
  10 Let no one be found among you who
  sacrifices their son or daughter in the fire,
  who practices divination or sorcery,
  interprets omens, engages in witchcraft, 11 or
  casts spells, or who is a medium or spiritist
  or who consults the dead.
#+END_SRC

+ Billy Graham :: "he oppresses
    he afflicts he influences he destroys he
    quotes and misquotes scripture he possesses he
    inflicts bodily injury he sells discord in the
    church he spreads false doctrine"

#+BEGIN_SRC text -n :async :results verbatim code
  "I believe that one of the problems in the
  world today that is not recognized is the
  great intensification and acceleration of evil
  in the world at this moment because the devil
  knows his time is short the coming of the Lord
  Jesus Christ may be drawing near and the
  scripture teaches that as the coming of the
  Lord draws near the activity of the devil will
  intensify."
#+END_SRC

#+BEGIN_SRC text -n :async :results verbatim code
  "Witchcraft is growing faster than any other
  religion in the western world and one reason I
  think that young people get involved is
  because it does get them involved. It's a
  return to nature in a sense of worship of the
  natural gods finding some power within
  themselves or broadening their minds."
#+END_SRC

- The father of fakery:
  - false miracles
    - Artificial intelligence
    - Medical technology
  - false spiritual experiences
    - Drugs
  - false tongues
    - https://mullikine.github.io/posts/imaginary-chimera-languages-with-codex/
  - false church
    - Social and cultural rules
  - false gospel
  - false plan of salvation
    - Immortality through technology
  - false trinity
  - false preachers
  - false prophets

He promises freedom liberty and life but he
produces only sorrow, slavery and death. He's
a deceiver.

#+BEGIN_SRC text -n :async :results verbatim code
  Mystery of iniquity
  Secret power of lawlessness
      [mystery]
  
      - 2 Thessalonians 2:8
  
  The doctrine of the Gentile church
      [mystery]
  
      - Romans 16:25–27
      - Ephesians 3:4–12
      - Colossians 1:25–27
  
      25 Now to him who is able to establish you
      in accordance with my gospel, the message
      I proclaim about Jesus Christ, in keeping
      with the revelation of the mystery hidden
      for long ages past, 26 but now revealed
      and made known through the prophetic
      writings by the command of the eternal
      God, so that all the Gentiles might come
      to the obedience that comes from[a] faith—
      27 to the only wise God be glory forever
      through Jesus Christ! Amen.
  
  The rapture
      [#New International Version]
  
      - 1 Corinthians 15:51-52
  
      51 Listen, I tell you a mystery: We will
      not all sleep, but we will all be changed—
      52 in a flash, in the twinkling of an eye,
      at the last trumpet. For the trumpet will
      sound, the dead will be raised
      imperishable, and we will be changed.
#+END_SRC


** The mystery of iniquity
What exactly is the mystery of iniquity (=KJV=)
or the secret power of lawlessness (=NIV=) that
is being restrained by the Holy Spirit?

The word mystery denotes something hidden for
a time before God chooses to reveal it.

Some “mysteries” revealed in the New Testament
include the doctrine of the Gentile church
(Romans 16:25–27; Ephesians 3:4–12; Colossians
1:25–27) and the rapture (1 Corinthians
15:51–52).

This particular “mystery” in 2 Thessalonians
2:7 concerns the working of lawlessness in the
world, leading to a worldwide rebellion
against God.

It works in secret right now, but it is
working.

The revelation of this lawlessness will
coincide with the revelation of the
Antichrist, mentioned in _2 Thessalonians 2:8_.

The man of sin’s rise to power will represent
a climax of lawlessness, a satanic movement
against the administration of God.

This secret, behind-the-scenes movement is as
yet restrained but waiting to be revealed.

The mystery of iniquity has been at work for a
long time—since Paul’s day—and, when it
finally erupts in all its hideousness, the
world will be shaken to its core.

The Antichrist, who leads the descent into
lawlessness, will set a new standard of
depravity.

The enormity of the acts of moral monsters
such as Stalin, Hitler, Pol Pot, Idi Amin,
Robespierre, and Caligula will pale in
comparison to the evil of the Antichrist.

** The doctrine of the Gentile church

** The rapture