#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+HUGO_BASE_DIR: /home/shane/var/smulliga/source/git/semiosis/semiosis-hugo
#+HUGO_SECTION: ./philosophy

#+TITLE: The Seeds of Speech - Language Origin and Evolution
#+DATE: <2021-09-17>
#+AUTHOR: Shane Mulligan
#+KEYWORDS: summary review philosophy linguistics

+ PDF :: http://libgen.lc/ads.php?md5=74BBECAE18249BD29CEE9F2FC103DE58

+ The mind is the _master manufacturer_
  + who divides the work to be executed into different processes.
  + modules in the mind
    + reasoning ability
    + spatial skills
    + language
    + etc.

+ The _biological bush_
  - 'As for humans, we are unquestionably a pure product of a certain aridity', it has been
    claimed (Coppens 1994: 69). After the catastrophe, our ape cousins were left in the lush
    and pleasant tree-terrain of the humid west. Our own ancestors were stranded in a
    relatively treeless savannah in the increasingly dry east, where they were forced to adapt,
    or die. An unfavourable climate forced a deprived species to live on its wits and, in the
    long run, develop language.

+ _social structure_ and _intimate interaction_
  - _guessing and gossip_, not _grooming in groups_: /Gossip/ rather than /grooming/ might
  have been promoted by several factors.

  Spoken language leaves the hands free for
  other activities, perhaps important in open
  savannah where humans possibly lived at one
  time (chapter 5). Sounds can be heard in the
  dark, and messages can be transmitted
  rapidly.

#+BEGIN_SRC text -n :async :results verbatim code
  phatic expression
  phatic communication
      [#linguistics]
  
      A phatic expression is communication which
      serves a social function, such as social
      pleasantries that don't seek or offer
      information of intrinsic value but can
      signal willingness to observe conventional
      local expectations for politeness.
#+END_SRC

+ _man of many wiles_ / _dogs may dissemble_
  + T. H. Huxley :: A man has no reason to
      be ashamed of having an ape for his
      grandfather. If there were an ancestor whom
      I should feel shame in recalling it would
      rather be a man ... who ... plunges into
      scientific questions with which he has no
      real acquaintance. _only to obscure_ them by
      an aimless rhetoric, and distract the
      attention of his hearers from the real point
      at issue by eloquent digressions and skilled
      appeals to religious prejudice.

  + _True_ *deceit* involves '_tactical_ *deception*'
    The extent of animal deception is only now
    becoming clear. But the deceit of dogs
    is not well-planned.: 'Acts from the
    normal repertoire of the agent, deployed
    such that another individual is likely to
    misinterpret what the acts signify, to the
    advantage of the agent' (R. W. Byrne and
    Whiten 1988, 1992: 612). Humans are very
    good at it. The ability to deceive is not
    necessarily a bad thing. This is a
    powerful skill, which may be used
    selfishly or unselfishly. To exercise it,
    it's necessary to mentally 'put oneself
    into another person's shoes'.
    
#+BEGIN_SRC text -n :async :results verbatim code
  theory of mind
      Humans can do this: they can imagine
      alternative possible worlds, and treat others
      as if they had 'mental states'.
      
      Those who can represent the minds of others in
      their own minds are said to have a theory of
      mind, something possessed by all normal
      humans.
      
      Some can talk, but they have great difficulty
      in fully understanding other people.
      
      Animals who possess a theory of mind are good
      at social manipulation.
  
  wile
      Devious or cunning stratagems employed in
      manipulating or persuading someone to do
      what one wants.
      "she didn't employ any feminine wiles to
      capture his attention"
  
  dissemble
      Conceal or disguise one's true feelings or
      beliefs.
      "an honest, sincere person with no need to
      dissemble"
  
      Disguise or conceal (a feeling or
      intention).
      "she smiled, dissembling her true emotion"
  
  mindblind
  mindblindness
      A few unfortunates suffer from a puzzling
      deficit, an inability to understand
      another's point of view.
  
      This condition is sometimes referred to as
      'mindblindness', and it is a major symptom
      of autism.
  
      To 'mindblind' humans, the world is a
      confusing place which they never 'get the
      hang of'.
#+END_SRC

+ _ruling the rules_
  - The permitted patterns or rules of all
    languages constantly change, and new words
    are continually coming into use. Yet
    language never collapses: the rules do not
    spiral out of control. Each new generation
    of children can cope with learning their
    language. And, with a bit of effort, all
    humans can learn any other human language,
    though they are baffled when faced with the
    communication systems of other species. It's
    an odd situation when it's impossible to
    find more than a few broad language
    universals. Some principles must rule the
    rules. Language has 'hidden secrets', reins
    which keep it in check, and linguists are
    who try to find out what they are. Let us
    consider the matter further.

  + _prohibitions vs preferences_
    - Broadly speaking, constraints are of two
      types, filters and preferences. Filters
      close off certain possibilities
      absolutely. Such prohibitions are true
      constraints. Preferences, on the other
      hand, provide channels which are easy to
      flow along. They turn attention away from
      some non-preferred, though possible,
      routes. Such pseudoconstraints are often
      difficult to separate from prohibitions.

    - To summarize, universals and constraints
      overlap: they are opposite sides of the
      same coin. Language contains two types
      of constraints: filters (real
      constraints) and preferences
      (pseudoconstraints). And these may work
      on at least two levels: that of general
      human abilities, and that of language.

#+BEGIN_SRC text -n :async :results verbatim code
  generativity
      The use of finite resources to produce an
      infinite variety of sentences
  
      Language has the property of generativity.
  
  language universal
      A feature common to all languages.
  
  absolute linguistic universal
      A feature common to all languages.
  
      Rare, unless one takes an over-broad view
      of the word 'universal'.
      
      Even when apparently found, they differ in
      details from language to language.
#+END_SRC

+ Unweaving the rainbow: _separating the strands_
  - Language has some similarities to the
  rainbow. Both can be partially separated
  from their surroundings: the rainbow from
  the clouds, and language from a general
  ability to think (chapter 4). And both
  language and the rainbow appear to be made
  out of various strands. To a poet, chopping
  it all up might seem like pointless
  pedantry. But for linguists concerned with
  language, this is a necessity, even if the
  result is unromantic.